<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Publishing Agreement</title>
    <style>
        body { font-family: 'serif'; line-height: 1.6; color: #333; padding: 40px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 40px; }
        .title { font-size: 24px; font-weight: bold; text-transform: uppercase; }
        .section { margin-bottom: 20px; text-align: justify; }
        .footer { margin-top: 60px; }
        .signature-box { border-top: 1px solid #333; width: 300px; margin-top: 40px; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Official Publishing Agreement</div>
        <p>The Curated Archive Publishing House</p>
    </div>

    <div class="section">
        <p>This Agreement is entered into on this <strong>{{ $date }}</strong> between <strong>The Curated Archive</strong> (hereinafter "The Publisher") and <strong>{{ $author }}</strong> (hereinafter "The Author").</p>
    </div>

    <div class="section">
        <h3>1. GRANT OF RIGHTS</h3>
        <p>The Author hereby grants and assigns to the Publisher the exclusive right to publish, distribute, and sell the Work titled <strong>"{{ $book_title }}"</strong> in all formats throughout the world.</p>
    </div>

    <div class="section">
        <h3>2. ROYALTIES</h3>
        <p>The Publisher shall pay to the Author a royalty based on the Net Sales of the Work as defined in the associated invoice and payment schedule.</p>
    </div>

    <div class="section">
        <h3>3. REPRESENTATIONS AND WARRANTIES</h3>
        <p>The Author represents and warrants that they are the sole author of the Work and that the Work is original and does not infringe upon any copyright or proprietary right of any third party.</p>
    </div>

    <div class="footer">
        <p>Generated by The Curated Archive Automation System.</p>
    </div>
</body>
</html>
